# Generated by Django 2.1.1 on 2018-10-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0004_auto_20181001_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activityrecord',
            old_name='activityType',
            new_name='activity_type',
        ),
    ]
